services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    volumes:
      - ./init_sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
