services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PAS}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:${POSTGRES_PORT}"
